version: "3"

services:
  jupyter:
    image: khan19/daskswarm:latest
    command: start-notebook.sh
    ports:
       - "8888:8888"
    networks:
      - distributed
    depends_on:
        - dscheduler
    deploy:
      placement:
        constraints: 
            - node.role == manager

  dscheduler:
    image: khan19/daskswarm:latest
    ports:
     - "8786:8786"
     - "9786:9786"
     - "8787:8787"
    command: start-dscheduler.sh
    networks:
      - distributed
    deploy:
      placement:
        constraints: 
           - node.role == manager

  dworker:
    image: khan19/daskswarm:latest
    command: start-dworker.sh
    ports:
       - "8789:8789"
    networks:
      - distributed
    depends_on:
        - dscheduler
    deploy:
      mode: global
      placement:
        constraints:
           - node.role == worker
    

networks:
  distributed:
    # Enable multi-host communication
    driver: overlay
    # Single host communication
    #driver: bridge
